collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3068497
  brandStrength: 0.5606019
  lightness: 0.8164211
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#2C2C2C'
    - '#6E6E6E'
    - '#B4B4B4'
  rhythmicContrast: 0.6568206
typography_spectrum: 0.1293315
layout_spectrum: 0.6911923
name: FRAGMENTEDLA
